import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Topmenu from "@/components/Topmenu";
import { getServerSession } from "next-auth/next";
import { authOption } from "@/app/api/auth/[...nextauth]/route";
import NextAuthProvider from "@/providers/NextAuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const NextAuthSession = getServerSession(authOption);
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider session={NextAuthSession}>
          <Topmenu />
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
